package app.ihm.panels;

import app.beans.Log;
import java.util.List;
import java.util.Vector;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author dingl01
 */
public class LogsIhm extends javax.swing.JPanel {

    public final static String IHMNAME = "logs";

    private final ItfIhmLogsIhm refIhm;

    public LogsIhm(ItfIhmLogsIhm refIhm) {
        this.refIhm = refIhm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsers = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLogs = new javax.swing.JList<>();
        txfUsername = new javax.swing.JTextField();
        txfSessionTime = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblSessionTime = new javax.swing.JLabel();
        lblUserFace = new javax.swing.JLabel();
        lblLogs = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        pnlUserFace = new app.ihm.panels.ImagePanel();

        lblUsers.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblUsers.setText("Logs");

        lstLogs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstLogs);

        txfUsername.setEditable(false);

        txfSessionTime.setEditable(false);

        lblUsername.setText("Username");

        lblSessionTime.setText("Session Time");

        lblUserFace.setText("Face of the user");

        lblLogs.setText("Logs");

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        pnlUserFace.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlUserFaceLayout = new javax.swing.GroupLayout(pnlUserFace);
        pnlUserFace.setLayout(pnlUserFaceLayout);
        pnlUserFaceLayout.setHorizontalGroup(
            pnlUserFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        pnlUserFaceLayout.setVerticalGroup(
            pnlUserFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(lblLogs)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSessionTime)
                            .addComponent(lblUsername))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfSessionTime, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUserFace)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlUserFace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(298, 298, 298)
                .addComponent(lblUsers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(92, 92, 92)
                        .addComponent(lblLogs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(lblUsers)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername)
                            .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSessionTime)
                            .addComponent(txfSessionTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(lblUserFace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlUserFace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        refIhm.navigateBetweenIhm(MainIhm.IHMNAME);
    }//GEN-LAST:event_btnBackActionPerformed

    public void fillList(List<Log> databaseLogs) {
        Vector vector = new Vector(databaseLogs);
        lstLogs.setListData(vector);
    }

    public JList<Log> getLstLogs() {
        return lstLogs;
    }

    public ImagePanel getPnlUserFace() {
        return pnlUserFace;
    }

    public JTextField getTxfSessionTime() {
        return txfSessionTime;
    }

    public JTextField getTxfUsername() {
        return txfUsername;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogs;
    private javax.swing.JLabel lblSessionTime;
    private javax.swing.JLabel lblUserFace;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JList<Log> lstLogs;
    private app.ihm.panels.ImagePanel pnlUserFace;
    private javax.swing.JTextField txfSessionTime;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables

}
