package app.ihm.panels;

import app.ihm.CustomCellRenderer;
import app.beans.Sequence;
import java.util.List;
import java.util.Vector;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author dingl01
 */
public class SequencesIhm extends javax.swing.JPanel {

    public final static String IHMNAME = "sequences";

    private final ItfIhmSequencesIhm refIhm;

    public SequencesIhm(ItfIhmSequencesIhm refIhm) {
        this.refIhm = refIhm;
        initComponents();
        lstActions.setCellRenderer(new CustomCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsers = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSequences = new javax.swing.JList<>();
        btnDeleteSequence = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstActions = new javax.swing.JList<>();
        txfUsername = new javax.swing.JTextField();
        lblSequence = new javax.swing.JLabel();
        lblActions = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();

        lblUsers.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblUsers.setText("Sequences");

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lstSequences.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstSequences);

        btnDeleteSequence.setText("Delete");
        btnDeleteSequence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSequenceActionPerformed(evt);
            }
        });

        lstActions.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lstActions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstActions);

        txfUsername.setEditable(false);

        lblSequence.setText("Sequences");

        lblActions.setText("Actions");

        lblUsername.setText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsers)
                .addGap(331, 331, 331))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(lblSequence)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblActions)
                .addGap(145, 145, 145))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeleteSequence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addGap(46, 46, 46)
                        .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblUsers)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSequence)
                    .addComponent(lblActions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteSequence)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        refIhm.navigateBetweenIhm(MainIhm.IHMNAME);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteSequenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSequenceActionPerformed
        // First check if a user is selected
        Sequence selectedSequence = lstSequences.getSelectedValue();
        if (selectedSequence != null) {
            // Deletes the user and get a list back if the user has correctly been removed.
            List<Sequence> newList = refIhm.deleteSequence(selectedSequence);
            if (newList != null) {
                // If the list is not null, then set it as the new list.
                fillList(newList);
            }
            // And set the current selection as NULL
            lstSequences.clearSelection();
            lstActions.clearSelection();

            // Clear the actions list content
            lstActions.setListData(new Vector());
        }


    }//GEN-LAST:event_btnDeleteSequenceActionPerformed
    public void fillList(List<Sequence> databaseSequences) {
        Vector vector = new Vector(databaseSequences);
        lstSequences.setListData(vector);
    }

    public JTextField getTxfUsername() {
        return txfUsername;
    }

    public JList<String> getLstActions() {
        return lstActions;
    }

    public JList<Sequence> getLstSequences() {
        return lstSequences;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteSequence;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblActions;
    private javax.swing.JLabel lblSequence;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JList<String> lstActions;
    private javax.swing.JList<Sequence> lstSequences;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables

    
}
